package ati;


import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import com.mongodb.MongoException;
import java.awt.Dimension;
import java.net.UnknownHostException;
import java.util.Arrays;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author geovanny
 */
public class Create extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    
    public Create() {
        initComponents();
        this.setPreferredSize(new Dimension(1500, 500));
        this.pack();
        jScrollPane1.setVisible(false);//Pelicula
        jScrollPane2.setVisible(false);//autor
        jScrollPane3.setVisible(false);//compania
        jButton1.setVisible(false);//Agregar dato
        jButton2.setVisible(false);//add autor
        jButton5.setVisible(false);//add autor
        jButton6.setVisible(false);//add autor
        jButton8.setVisible(false);//add autor
        jButton9.setVisible(false);//add autor
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Introducir Pelicula");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(670, 350, 260, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Genero", "Director", "Franquicia", "Pais", "AnoEstreno", "Duracion(min)", "Compania productora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(110);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 1410, 40);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nombre Autor", "Apellido 1", "Apellido 2"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 160, 630, 170);

        jButton2.setText("Agregar autor");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 340, 150, 40);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nombre", "Ano Fundacion", "Sitio Web"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(60, 100, 720, 50);

        jButton3.setText("Agregar pelicula");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(130, 80, 170, 25);

        jButton4.setText("Agregar compania");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(400, 80, 200, 25);

        jButton5.setText("Atras");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(780, 200, 110, 40);

        jButton6.setText("Introducir Franquicia");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(700, 390, 190, 40);

        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(800, 100, 100, 30);

        jButton9.setText("Delete by name");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(920, 100, 160, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    try {
     MongoClient mongoClient = new MongoClient();
    
    DB database = mongoClient.getDB("ATIDB");
      
      //Gets a collection with a given name.
        //If the collection does not exist, a new collection is created.
      DBCollection collection = database.getCollection("Movies");
      
      //Create and insert document to collection
      DBObject document = new BasicDBObject();
      document.put("Nombre", jTable1.getModel().getValueAt(0, 0));
      document.put("Genero", jTable1.getModel().getValueAt(0, 1));
      document.put("Director", jTable1.getModel().getValueAt(0, 2));
      document.put("Franquicia", jTable1.getModel().getValueAt(0, 3));
      document.put("Pais", jTable1.getModel().getValueAt(0, 4));
      document.put("Ano de estreno", jTable1.getModel().getValueAt(0, 5));
      document.put("Duracion", jTable1.getModel().getValueAt(0, 6));
      document.put("Compania Productora", jTable1.getModel().getValueAt(0, 7));
      
      DBObject autores = new BasicDBObject();;
      int i=0;
      for(; i<(jTable2.getModel().getRowCount());i++){
      autores = new BasicDBObject();
      autores.put("Nombre",jTable2.getModel().getValueAt(i, 0) );
      autores.put("Apellido 1",jTable2.getModel().getValueAt(i, 1) );
      autores.put("Apellido 2",jTable2.getModel().getValueAt(i, 2) );
      document.put("Autor"+String.valueOf(i+1), autores);
      }
     
      
      
      
      
      //Saves a document to the database
      collection.insert(document);
      
      //Queries for all objects in this collection
      DBCursor dbCursor = collection.find();
      DBObject record = null;
      
      while (dbCursor.hasNext()) {
        record = dbCursor.next();
        System.out.println(record);
      }
      
    } catch (MongoException e) {
      e.printStackTrace();
    }
  
       
      
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
      DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
      model.addRow(new Object[]{"Nombre Autor", "Apellido 1", "Apellido 2"});
  
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jButton1.setVisible(false);//Agregar dato
        jButton2.setVisible(false);//add autor  
        
        jButton3.setVisible(false);//
        jButton4.setVisible(false);//
        jScrollPane1.setVisible(false);//
        jScrollPane2.setVisible(false);//Pelicula
        jScrollPane3.setVisible(true);//autor
        jButton5.setVisible(true);//add autor 
        jButton6.setVisible(true);//add autor
        
        
        
        

      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        jButton1.setVisible(true);//Agregar dato
        jButton2.setVisible(true);//add autor  
        jButton3.setVisible(false);//
        jButton4.setVisible(false);//
        jButton5.setVisible(true);//add autor 
        jScrollPane1.setVisible(true);//Pelicula
        jScrollPane2.setVisible(true);//autor
        jButton8.setVisible(true);//add autor
        jButton9.setVisible(true);//add autor
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
     jScrollPane1.setVisible(false);//Pelicula
        jScrollPane2.setVisible(false);//autor
        jScrollPane3.setVisible(false);//compania
        jButton1.setVisible(false);//Agregar dato
        jButton2.setVisible(false);//add autor
         jButton3.setVisible(true);//Agregar dato
        jButton4.setVisible(true);//add autor
        jButton5.setVisible(false);//add autor
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     MongoClient mongoClient = new MongoClient();
    
    DB database = mongoClient.getDB("ATIDB");
      
      //Gets a collection with a given name.
        //If the collection does not exist, a new collection is created.
      DBCollection collection = database.getCollection("CompaniaProductora");
      
      
      //Create and insert document to collection
      DBObject document = new BasicDBObject();
      document.put("Nombre", jTable3.getModel().getValueAt(0, 0));
      document.put("Ano", jTable3.getModel().getValueAt(0, 1));
      document.put("Web", jTable3.getModel().getValueAt(0, 2));
        //Saves a document to the database
      collection.insert(document);
      
      //Queries for all objects in this collection
      DBCursor dbCursor = collection.find();
      DBObject record = null;
      
      while (dbCursor.hasNext()) {
        record = dbCursor.next();
        System.out.println(record);
      }
      
      
      
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        
        
        
        
     MongoClient mongoClient = new MongoClient();
    
    DB database = mongoClient.getDB("ATIDB");
      
      //Gets a collection with a given name.
        //If the collection does not exist, a new collection is created.
      DBCollection collection = database.getCollection("Movies");
      
      //Create and insert document to collection
      DBObject document = new BasicDBObject();
      document.put("Nombre", jTable1.getModel().getValueAt(0, 0));
      document.put("Genero", jTable1.getModel().getValueAt(0, 1));
      document.put("Director", jTable1.getModel().getValueAt(0, 2));
      document.put("Franquicia", jTable1.getModel().getValueAt(0, 3));
      document.put("Pais", jTable1.getModel().getValueAt(0, 4));
      document.put("Ano de estreno", jTable1.getModel().getValueAt(0, 5));
      document.put("Duracion", jTable1.getModel().getValueAt(0, 6));
      document.put("Compania Productora", jTable1.getModel().getValueAt(0, 7));
      
     
      
    BasicDBObject query = new BasicDBObject();
    query.put("Nombre", jTable1.getModel().getValueAt(0, 0) );
 

 
BasicDBObject updateObject = new BasicDBObject();
updateObject.put("$set", document);
 
collection.update(query, updateObject);





      
  
        
        
        
 

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         MongoClient mongoClient = new MongoClient();
    
    DB database = mongoClient.getDB("ATIDB");
      
      //Gets a collection with a given name.
        //If the collection does not exist, a new collection is created.
      DBCollection collection = database.getCollection("Movies");
       BasicDBObject query = new BasicDBObject();
    query.put("Nombre", jTable1.getModel().getValueAt(0, 0) );
    
    collection.remove(query);
    
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
